apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: olumoko-voting-app
data:
  logstash.conf: |-
    input {
      beats {
        port => "9600"
      }
    }

    filter {
      if [index_prefix] == "eshopee-logs" {
        json {
          source => "message"
          skip_on_invalid_json => true
        }
      }
      
      # Do not expose index_prefix field to Elasticsearch
      mutate {
        # @metadata is not exposed outside of Logstash by default.
        add_field => { "[@metadata][index_prefix]" => "%{index_prefix}-%{+YYYY.MM.dd}" }
        # Since we added index_prefix to metadata, we no longer need ["index_prefix"] field.
        remove_field => ["index_prefix"]
        remove_field => ["host"]
      }
    }

    output {
      # Uncomment this line to investigate the generated events by Logstash.
      # stdout { codec => rubydebug }
      elasticsearch {
        hosts => "elasticsearch:9200"
        template_overwrite => false
        manage_template => false
        # The events will be stored in Elasticsearch under the previously defined index_prefix value.  
        index => "%{[@metadata][index_prefix]}"
        sniffing => false
      }
    }
